name: native_flutter_proxy
description: A flutter plugin to read and set network proxy info from native.
version: 0.2.0
homepage: https://github.com/victorblaess/native_flutter_proxy

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.victorblaess.native_flutter_proxy
        pluginClass: FlutterProxyPlugin
      ios:
        pluginClass: FlutterProxyPlugin
